---
- name: Create the directory where rpm will be copied
  file:
    path: "{{ docker_dest_dir }}"
    state: directory
    mode: '0755'

- name: unpack docker tar
  unarchive: 
    src: files/docker.tar
    dest: "{{ docker_dest_dir }}"
    remote_src: no

- name: try to install docker offline
  command: rpm -ivh --replacefiles --replacepkgs *.rpm
  args:
    chdir: "{{ docker_dest_dir }}"
