---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and not offline_mode

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' and not offline_mode

- name: Check if mandatory variables are defined
  assert:
    that:
      - " docker_mount_dir is not none and docker_mount_dir is defined"

- include_tasks: install-docker.yml
  when: not offline_mode | bool

- include_tasks: install-docker-offline.yml
  when: offline_mode | bool

- include_tasks: install-docker-compose.yml
  when: not offline_mode | bool and docker_install_compose | bool

- include_tasks: install-docker-compose-offline.yml
  when: offline_mode | bool and docker_install_compose | bool

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-CisCompliance.yml
  when: docker_cis | bool

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-users.yml
  when: docker_users | length > 0
