---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check if mandatory variables are defined
  assert:
    that:
      - " docker_mount_dir is not none and docker_mount_dir is defined"

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Copy Docker daemon.json file - Docker Configuration requirements CIS section 1
  copy:
      src: files/daemon.json
      dest: /etc/docker/daemon.json
  when: docker_cis | bool 

- name: Copu audit.rule and restart auditd service - Docker Configuration requirements CIS section 2
  copy:
      src: files/audit.rules
      dest: /etc/audit/audit.rules
  notify: restart auditd
  when: docker_cis | bool

- name: Copy fips-module.conf - Configure Docker daemon to use FIPS 140-2 cryptographic module
  copy:
      src: files/fips-module.conf
      dest: /etc/systemd/system/docker.service.d/fips-module.conf
  when: docker_edition == 'ee'

- name: check if there's a dedicated mount for docker
  mount:
      path: "{{ docker_mount_dir }}"
      src: "{{ docker_device_src }}"
      state: present
      fstype: xfs
  when: docker_cis | bool

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
