---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and not offline_mode

- name: Check if mandatory variables are defined
  assert:
    that:
      - " docker_mount_dir is not none and docker_mount_dir is defined"

- name: Install Docker (online mode).
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker
  when: not offline_mode | bool

- include_tasks: docker-offline-inst.yml
  when: offline_mode | bool


- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- include_tasks: docker-CisCompliance.yml
  when: docker_cis | bool

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: docker-compose.yml
  when: docker_install_compose | bool and not offline_mode | bool

- include_tasks: docker-compose-offline-inst.yml
  when: docker_install_compose | bool and offline_mode | bool

- include_tasks: docker-users.yml
  when: docker_users | length > 0
