---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker GPG key.
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present
  when: docker_edition == 'ce' and offline_mode == '1'

- name: Add Docker EE URL into yum (Only for Docker EE)
  shell: 'echo {{ docker_ee_url }} > /etc/yum/vars/dockerurl'
  when: docker_edition == 'ee' and offline_mode == '1'

- name: Store OS version into dockerversion file (Only for Docker EE)
  shell: 'echo {{ docker_rhat_version }} > /etc/yum/vars/dockerosversion'
  when: docker_edition == 'ee' and offline_mode == '1'

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644
  when: docker_edition == 'ce' and offline_mode == '1'

- name: Add Docker enterprise repository
  get_url:
    url: "{{ docker_ee_repo_url }}"
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    owner: root
    group: root
    mode: 0644
  when: docker_edition == 'ee' and offline_mode == '1'

- name: Configure Docker Edge repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-edge'
    option: enabled
    value: '{{ docker_yum_repo_enable_edge }}'
  when: offline_mode == '1'

- name: Configure Docker Test repo.
  ini_file:
    dest: '/etc/yum.repos.d/docker-{{ docker_edition }}.repo'
    section: 'docker-{{ docker_edition }}-test'
    option: enabled
    value: '{{ docker_yum_repo_enable_test }}'
  when: offline_mode == '1'

- name: Install containerd separately (CentOS 8).
  package:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    state: present
  when: ansible_distribution_major_version | int == 8

- name: Enable extra repository for RHEL
  ini_file:
    dest: /etc/yum.repos.d/redhat-rhui.repo
    section: rhui-rhel-7-server-rhui-extras-rpms
    option: enabled
    value: '1'
  when: offline_mode == '1'

- name: Reload yum cache (Only for Docker EE)
  shell: 'yum makecache fast'
  when: docker_edition == 'ee' and offline_mode == '1'
